
server:
  port: 8080
#设置git访问
#spring:
#  application:
#    name: configServer
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/forezp/SpringcloudConfig/
          
#设置本地访问        
spring:
  application:
    name: configServer #配置服务名称
  profiles:
    active: native #设置为本地启动的方式，而不是通过git
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config 
#注册中心指向start    
eureka:
  instance:
    instance-id: configServer
    appname: ${spring.application.name}
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:8100/eureka/
#注册中心指向end
                     