server:
  port: 8818

spring:
 application:
   name: adminServer

# 安全中心配置
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"  #<2>
#  endpoint:
#    health:
#      show-details: ALWAYS
# end::configuration-eureka[]

# 添加到注册中心           
eureka:
  instance:
    instance-id: adminServer
    appname: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8100/eureka/  
      instance:
      preferIpAddress: true
    register-with-eureka: true
    fetch-registry: false  

---
spring:
  profiles: insecure
#
#---
#spring:
#  profiles: secure
#  security:
#    enable: false
#    user:
#      name: admin
#      password: 123123
   
   
#    metadata-map:
#      user.name: "admin" #These two are needed so that the server
#      user.password: "862112" #can access the protected client endpoints

     
