server:
  port: 3000
spring:
  application:
    name: eurekaClinte
    
#注册中心指向start    
eureka:
  instance:
    instance-id: eurekaClinte
    appname: ${spring.application.name}
  client: 
    service-url: 
      defaultZone: http://127.0.0.1:8100/eureka/
      instance:
      preferIpAddress: true
#注册中心指向end
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS
#配置当前服务start 
  application:
    name: configServer #配置服务名称
  profiles:
    active: native #设置为本地启动的方式，而不是通过git
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config  
#配置当前服务end           